### ISSUE TITLE
Call to random() in hash_table may not be portable

### ISSUE THREAD

**Issue by dibyendumajumdar** [anholt/hash_table#1]
Hi,

I am not sure if random() is available on Windows. I had no problem using the library on Linux, but on Windows I am getting undefined reference. Also random() is not standard C. Can it be replaced by standard C function such as rand()?

Thanks and Regards

**Comment by anholt** [comment]
That would be up to you evaluate as the user of the hash_table_random_entry() function.  Or delete that function if you're not using it.

**Comment by dibyendumajumdar** [comment]
Yes well I have commented it out.
